name: ecommerce
description: "An e commerce app using flutter."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  animated_text_kit: ^4.2.1
  http: ^0.13.3
  provider: ^5.0.0
  flutter_secure_storage: ^5.0.0-beta.5
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  getwidget: ^2.0.3
  flutter_svg: ^0.22.0
  flutter_rating_bar: ^4.0.0
  webview_flutter: ^2.0.12
  font_awesome_flutter: ^9.1.0
  google_sign_in: 5.0.7
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
